# Lecture
- Scripting
    - Why write a script?
        - I'd like to hear why the class things we should have
          analytical scripts. Make sure to discuss the reading.
        - Reproducibility v Replicability
        - Ease/completeness of communication 
        - Ease of sharing ideas (I'm sharing scripts with you)
    - You need to understand: Working Directory
- More Data Import:
    - SAS
    - Google Sheets
- Introducing R Markdown
    - Say goodbye to Word!
    - We are going to use this throughout the semester.
    - I don't expect you to become an expert with it.
    - I do expect you to become competent with it.
    - This is an extension of "a script" in that it combines your CODE
      with your WORDS.
    - Demonstrate that we can output to multiple formats
        - This class will focus on HTML reports/slideshows.

# Lab: Your First Notebook
   - Introduce an Analytical Template
   - Create a set of teams (pair programming)
   - Using a DIFFERENT Cards Against Humanity Survey . . . . repeat the
     last challenge, but ask the students to implement it using R Markdown.
